const books = [
  {
    id: 1,
    title: "Harry Potter and the Philosopher's Stone",
    author: "J. K. Rowling",
    category: "Fantasy",
    pages: 223,
    recommends: true,
    read: true,
  },
  {
    id: 2,
    title: "Harry Potter and the Chamber of Secrets",
    author: "J. K. Rowling",
    category: "Fantasy",
    pages: 251,
    recommends: false,
    read: true,
  },
  {
    id: 3,
    title: "Harry Potter and the Prisoner of Azkaban",
    author: "J. K. Rowling",
    category: "Fantasy",
    pages: 317,
    recommends: false,
    read: false,
  },
  {
    id: 4,
    title: "Harry Potter and the Goblet of Fire",
    author: "J. K. Rowling",
    category: "Fantasy",
    pages: 636,
    recommends: false,
    read: false,
  },
  {
    id: 5,
    title: "Harry Potter and the Order of the Phoenix",
    author: "J. K. Rowling",
    category: "Fantasy",
    pages: 766,
    recommends: false,
    read: false,
  },
  {
    id: 6,
    title: "Harry Potter and the Half-Blood Prince",
    author: "J. K. Rowling",
    category: "Fantasy",
    pages: 607,
    recommends: true,
    read: true,
  },
  {
    id: 7,
    title: "Harry Potter and the Deathly Hallows",
    author: "J. K. Rowling",
    category: "Fantasy",
    pages: 607,
    recommends: false,
    read: false,
  },
  {
    id: 8,
    title: "The Fault in Our Stars",
    author: "John Green",
    category: "Romance",
    pages: 313,
    recommends: false,
    read: false,
  },
  {
    id: 9,
    title: "The Hating Game: A Novel",
    author: "Sally Thorne",
    category: "Romance",
    pages: 416,
    recommends: false,
    read: false,
  },
  {
    id: 10,
    title: "Call Me by Your Name",
    author: "André Aciman",
    category: "Romance",
    pages: 256,
    recommends: false,
    read: false,
  },
  {
    id: 11,
    title: "'Salem's Lot",
    author: "Stephen King",
    category: "Horror",
    pages: 439,
    recommends: false,
    read: true,
  },
  {
    id: 12,
    title: "Carrie",
    author: "Stephen King",
    category: "Horror",
    pages: 199,
    recommends: false,
    read: false,
  },
  {
    id: 13,
    title: "It",
    author: "Stephen King",
    category: "Horror",
    pages: 1138,
    recommends: true,
    read: true,
  },
];

module.exports = books;
